### ISSUE TITLE
SyntaxError: Unexpected token { in contentful-cli/node_modules/locate-path/index.js:41

### ISSUE THREAD

**Issue by smohadjer** [contentful/contentful-cli#1535]
I just installed contetnful-cli from npm ("version": "1.14.15") and when I run contentful --help I get this error:

````
mb12:neoperl-contentful-migration-scripts sm$ contentful --help
/usr/local/Cellar/contentful-cli/1.9.30/libexec/lib/node_modules/contentful-cli/node_modules/locate-path/index.js:41
		} catch {
		        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/contentful-cli/1.9.30/libexec/lib/node_modules/contentful-cli/node_modules/find-up/index.js:3:20)
````

We were running our contentful migration scripts until recently without any problems, but since a few days this error shows whenever we deploy any migration script. Any idea what has gone wrong?

**Comment by smohadjer** [comment]
Turned out the reason was using an old version of nodejs.
