### ISSUE TITLE
403 error on import

### ISSUE THREAD

**Issue by mortscode** [contentful/contentful-cli#158]
## Expected Behavior

Enter `contentful login` and use the OAuth token to authenticate.
In terminal, enter `contentful space import --config config.json` and import a Content Type into my environment.

config.json:
```
{
  "spaceId": "[SPACE ID]",
  "environmentId": "[ENVIRONMENT ID]",
  "managementToken": "[MANAGEMENT TOKEN]",
  "contentFile": "path/to/content-type.json",
  "contentModelOnly": true
}
```

## Actual Behavior

```
The following 1 errors and 0 warnings occurred:

16:59:07 - AccessDenied: Status: 403 - Forbidden - Message: Forbidden - Request ID: ###

Stored the detailed error log file at:path/to/error-log.json
🚨  Error: Errors occured
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ContentfulMultiError: Errors occured                                                                                                                                                  │
│      at then (/usr/local/lib/node_modules/contentful-cli/node_modules/contentful-import/dist/index.js:202:28)                                                                         │
│      at tryCatcher (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/util.js:16:23)                                                                        │
│      at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:517:31)                                             │
│      at Promise._settlePromise (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:574:18)                                                        │
│      at Promise._settlePromise0 (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:619:10)                                                       │
│      at Promise._settlePromises (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:699:18)                                                       │
│      at _drainQueueStep (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:138:12)                                                                 │
│      at _drainQueue (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:131:9)                                                                      │
│      at Async._drainQueues (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:147:5)                                                               │
│      at Immediate.Async.drainQueues (/usr/local/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:17:14)                                                      │
│      at runCallback (timers.js:810:20)                                                                                                                                                │
│      at tryOnImmediate (timers.js:768:5)                                                                                                                                              │
│      at processImmediate [as _immediateCallback] (timers.js:745:5)
```

## Possible Solution

`contentful login` OAuth would give me permissions for importing data

## Steps to Reproduce
1. `npm install -g contentful-cli`
2. `contentful login` (OAuth via browser token)
3. create a `contentful-config.json` file
4. `contentful space import --config contentful-config.json`

## Environment

Node Version: v8.16.0
Npm Version: 6.9.1
Operating System: Darwin [username] 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
Package Version: contentful-cli 0.33.2

-   **Language Version**: en-us
-   **Package Manager Version**:
-   **Browser Version**:
-   **Operating System**: OSX 10.14.5
-   **Package Version**:

**Comment by Khaledgarbaya** [comment]
Hi @mortscode did you try without the config file like this
```sh
contentful space import --space-id=<spae-id> --management-token=<token>
```
If the same this still happen make sure that you have the correct permission on the space

**Comment by makinwab** [comment]
Let's know if you're still facing this issue. In the meantime, I'll be closing this.
