### ISSUE TITLE
Space export: BadRequest: Status: 400 - Bad Request - Message: Response size too big. Maximum allowed response size: 7340032b

### ISSUE THREAD

**Issue by marcin-bo** [contentful/contentful-cli#176]
## Expected Behavior

Space export should get all data and models.

## Actual Behavior

I'm getting the following error message: 
`BadRequest: Status: 400 - Bad Request - Message: Response size too big. Maximum allowed response size: 7340032b. - Request ID: 7ec689c…`
```
 ✔ Initialize client (1s)
 ❯ Fetching data from space
   ✔ Connecting to space (2s)
   ✔ Fetching content types data (1s)
   ✔ Fetching editor interfaces data (6s)
   ✖ Fetching content entries data (2s)
     → BadRequest: Status: 400 - Bad Request - Message: Response size too big. Maximum allowed response size: 7340032b. - Request ID: 7ec689c…
     Fetching assets data
     Fetching locales data
     Fetching webhooks data
     Fetching roles data
   Download assets
   Write export log file


The following 1 errors and 1 warnings occurred:

13:20:70 - Rate limit error occurred. Waiting for 1541 ms before retrying...
13:20:81 - Error: Status: 400 - Bad Request - Message: Response size too big. Maximum allowed response size: 7340032b. - Request ID: 7ec689cf8488b73ee7f114a0b351521a

Stored the detailed error log file at:
<PATH_TO_ERROR_LOG>.json
🚨  Error: Errors occured
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ContentfulMultiError: Errors occured                                                                                                       │
│      at /usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/contentful-export/dist/index.js:203:28 │
│      at tryCatcher                                                                                                                         │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/util.js:16:23)            │
│      at Promise._settlePromiseFromHandler                                                                                                  │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:517:31)        │
│      at Promise._settlePromise                                                                                                             │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:574:18)        │
│      at Promise._settlePromise0                                                                                                            │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:619:10)        │
│      at Promise._settlePromises                                                                                                            │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:699:18)        │
│      at _drainQueueStep                                                                                                                    │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:138:12)          │
│      at _drainQueue                                                                                                                        │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:131:9)           │
│      at Async._drainQueues                                                                                                                 │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:147:5)           │
│      at Immediate.Async.drainQueues [as _onImmediate]                                                                                      │
│ (/usr/local/Cellar/contentful-cli/1.1.0/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:17:14)           │
│      at processImmediate (internal/timers.js:439:21)
```

## Possible Solution

Reduce the number of entries per page in the client and keep the include value (see:
[https://github.com/contentful/contentful.js/issues/336](https://github.com/contentful/contentful.js/issues/336))

## Steps to Reproduce

1. Have large data set in the space
2. Run the command:
`contentful space export --space-id <spaceId> --management-token <token> --include-drafts 1 --skip-roles 1 --skip-webhooks 1`

## Context

I have large set of data and I want to export it and then import it to another space.

## Environment

-   **Language Version**:
-   **Package Manager Version**:
-   **Browser Version**:
-   **Operating System**: MacOS 10.14.6
-   **Package Version**: 1.1.0

**Comment by Khaledgarbaya** [comment]
Hi @marcin-bo,
You can add `--max-allowed-limit  100` to reduce the number of entities to fetch per request. The default is 1000.
