### ISSUE TITLE
Validation error on import

### ISSUE THREAD

**Issue by jasonfma** [contentful/contentful-cli#186]
## Expected Behavior
Able to import to a space from an export of a space.

## Actual Behavior

Error on import
```

┌──────────────────────────────────────────────────┐
│ The following entities are going to be imported: │
├────────────────────────────────┬─────────────────┤
│ Content Types                  │ 13              │
├────────────────────────────────┼─────────────────┤
│ Editor Interfaces              │ 13              │
├────────────────────────────────┼─────────────────┤
│ Entries                        │ 533             │
├────────────────────────────────┼─────────────────┤
│ Assets                         │ 103             │
├────────────────────────────────┼─────────────────┤
│ Locales                        │ 1               │
├────────────────────────────────┼─────────────────┤
│ Webhooks                       │ 0               │
└────────────────────────────────┴─────────────────┘
 ✖ Validating content-file
   → assets:8 - Get further details in the error log file
   Initialize client
   Checking if destination space already has any content and retrieving it
   Apply transformations to source data
   Push content to destination space


The following 1 errors and 0 warnings occurred:

16:42:70 - ValidationError: assets:8 - Get further details in the error log file

Stored the detailed error log file at:
/Users/jason/dev/cleo-app/contentful-import-error-log-z2jxtpga2adb-2019-10-22T16-42-59.json
🚨  Error: Errors occured
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ContentfulMultiError: Errors occured                                                                                               │
│      at then                                                                                                                       │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/contentful-import/dist/index.js:202:28)     │
│      at tryCatcher                                                                                                                 │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/util.js:16:23)          │
│      at Promise._settlePromiseFromHandler                                                                                          │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:547:31)      │
│      at Promise._settlePromise                                                                                                     │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:604:18)      │
│      at Promise._settlePromise0                                                                                                    │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:649:10)      │
│      at Promise._settlePromises                                                                                                    │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:729:18)      │
│      at _drainQueueStep                                                                                                            │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:93:12)         │
│      at _drainQueue                                                                                                                │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:86:9)          │
│      at Async._drainQueues                                                                                                         │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:102:5)         │
│      at Immediate.Async.drainQueues [as _onImmediate]                                                                              │
│ (/Users/jason/.nvm/versions/node/v10.16.3/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:15:14)         │
│      at runCallback (timers.js:705:18)                                                                                             │
│      at tryOnImmediate (timers.js:676:5)                                                                                           │
│      at processImmediate (timers.js:658:5)                                                                                         │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

## Steps to Reproduce

1. export from space in same account with download assets option
2. import to another space in the same account
3. see error

## Context

Trying to export an environment and import that into another environment. Basically migrate the content.

## Environment

Node: 10.16.3
package: 1.1.3

**Comment by jasonfma** [comment]
Noticed that the entities didn't have a preview icon in the source space. Opened them, and it somehow triggered a re-processing. Re-exported, and now import is working.
