### ISSUE TITLE
transformEntriesToType fails with Bad Request

### ISSUE THREAD

**Issue by benmarch** [contentful/contentful-cli#195]
## Expected Behavior

Using transformEntriesToType should create new entries of a specific type based on existing entries of a different type.

## Actual Behavior

I get two errors for every existing entry: a 400 and and 404. It seems to attempt a PUT to the new entry's URL, but this responds with a 400. It's difficult to tell from the error file because of the formatting, but it might be doing a GET on the URL first, which then responds with a 404. I can also see a double forward slash in the URL; not sure if that has any negative effects. 

```
{
  "status": 400,
  "statusText": "Bad Request",
  "message": "The content type you sent could not be found or was not activated.",
  "details": {},
  "request": {
    "url": "https://api.contentful.com:443/spaces/XXXXX/environments/master//entries/1697472545",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/vnd.contentful.management.v1+json",
      "X-Contentful-User-Agent": "app contentful.cli/1.1.5; feature space-migration; sdk contentful-management.js/5.2.1; platform node.js/v8.6.0; os macOS/15.6.0;",
      "Authorization": "Bearer ...0IEhk",
      "user-agent": "node.js/v8.6.0",
      "Accept-Encoding": "gzip",
      "X-Contentful-Version": 0,
      "X-Contentful-Content-Type": "expandableType",
      "Content-Length": 3189
    },
    "method": "put",
    "payloadData": "XXX",
  "requestId": "c10555a53e6051e0d1086d927342947d"
}
    at errorHandler (xxx/node_modules/contentful-management/dist/contentful-management.node.js:13134:15)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)NotFound: {
  "status": 404,
  "statusText": "Not Found",
  "message": "The resource could not be found.",
  "details": {
    "type": "Entry",
    "id": "1697472545",
    "environment": "master",
    "space": "xxxxx"
  }
```

## Steps to Reproduce

I just ran the following migration:

```js
const MurmurHash3 = require('imurmurhash')

module.exports = (migration, context) => {
  migration.transformEntriesToType({
    sourceContentType: 'detailSummary',
    targetContentType: 'expandableType',
    shouldPublish: true,
    updateReferences: true,
    removeOldEntries: false,
    identityKey: fields => {  
      return MurmurHash3(fields.title['en-US'].toString()).result().toString()
    },
    transformEntryForLocale: (fromFields, locale) => {
      return {
        contentName: fromFields.title[locale],
        title: fromFields.summary[locale],
        bodyContent: fromFields.details[locale],
        variant: 'expandable-box'
      }
    }
  })
}

```
## Environment

-   **Node Version**: 8.6.0
-   **Package Manager Version**: 6.1.0
-   **Operating System**: Darwin C02PLJWEG8WN 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
-   **Package Version**: 1.1.5

**Comment by benmarch** [comment]
This was my fault, I had the `targetContentType` wrong (it should be `expandableContent`). It would be nice to have a validation to ensure that both the source and target exist, though.
