### ISSUE TITLE
Exception running 'contentful space list'

### ISSUE THREAD

**Issue by andresfcamacho** [contentful/contentful-cli#458]
## Expected Behavior

I'm running this command:
```
contentful space list
```

I expect to get the list of spaces on my account. 

## Actual Behavior
I get this:
```
/usr/local/Cellar/contentful-cli/1.4.11/libexec/lib/node_modules/contentful-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:85
      } catch {
              ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/Cellar/contentful-cli/1.4.11/libexec/lib/node_modules/contentful-cli/node_modules/fs-extra/lib/mkdirs/index.js:3:44)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
```

## Steps to Reproduce

See above.

## Context

I'm getting started with the CLI. My goal is to be able to export, create a new space and re-import.

## Environment
cli version: 1.4.11
node: v8.12.0
npm: 6.4.1
OS: Darwin xxxx 18.7.0 Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64 x86_64

**Comment by matthew-contentful** [comment]
Can you try again with node v10? The cli requires Node LTS
