### ISSUE TITLE
Cannot find module 'contentful-management' on all contentful CLI commands

### ISSUE THREAD

**Issue by alex-greco-harrys** [contentful/contentful-cli#55]
## Expected Behavior

- contentful to function when commands in the terminal are run

## Actual Behavior

- All commands that are used with contentful result in the following error.
- When I follow the path (...nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/dist/utils/contentful-clients.js) I am able to read the contentful-clients.js file, where I can see the script requiring the contentful-management file.

```
<MACHINE>:<FOLDER> <USER>$ contentful --help
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'contentful-management'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (<USER>.nvm/versions/node/v9.11.1/lib/node_modules/contentful-cli/dist/utils/contentful-clients.js:11:29)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

## Steps to Reproduce

1. Download nvm and use version 9.11.1 of node.
2. Use brew to install yarn.
3. Run yarn install with this as config for contentful:
`contentful@^6.1.0:
  version "6.1.1"
  resolved "https://registry.yarnpkg.com/contentful/-/contentful-6.1.1.tgz#75fd951257728d9de1b9a2d04b9d268a6d8d1a0d"
  dependencies:
    "@contentful/axios" "^0.18.0"
    contentful-resolve-response "^1.1.4"
    contentful-sdk-core "^6.0.0-beta0"
    json-stringify-safe "^5.0.1"
    lodash "^4.17.5"`
4. Try to run any contentful command and run into error above

## Environment

Node Version: v9.11.1
Npm Version: 5.6.0
Nvm Version: 0.33.11
Operating System: Darwin Kernel Version 17.6.0
Package Version: contentful@6.1.1 

-   **Package Manager Version**: 5.6.0
-   **Browser Version**: 67.0.3396.99
-   **Operating System**: Mac 10.13.5
-   **Package Version**: contentful@6.1.1

**Comment by frankievalentine** [comment]
+1 to this. Just installed the cli.

Node Version: v10.7
npm Version: 6.2

Operating System: MacOS 10.13.6

`contentful guide

internal/modules/cjs/loader.js:583
    throw err;
    ^

Error: Cannot find module 'contentful-management'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/contentful-cli/dist/utils/contentful-clients.js:11:29)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

**Comment by axe312ger** [comment]
We are on it.
