### ISSUE TITLE
Resource cannot be found when exporting space content

### ISSUE THREAD

**Issue by sahellebusch** [contentful/contentful-cli#579]
## Expected Behavior
 
Expecting an export from the space.

## Actual Behavior
Receiving a 404 error: `404 - Not Found - Message: The resource could not be found.`.

## Steps to Reproduce
1. Created new access token
2. `contentful login --management-token [TOKEN]`
3. `contentful space export --space-id [SPACE_ID]`
4. 💥 

## Context

The output:

```bash
contentful space export

  ✔ Initialize client (1s)
  ❯ Fetching data from space
    ✔ Connecting to space (1s)
    ✔ Fetching content types data (1s)
    ✔ Fetching tags data (1s)
    ✔ Fetching editor interfaces data (1s)
    ✔ Fetching content entries data (1s)
    ✔ Fetching assets data (1s)
    ✔ Fetching locales data (1s)
    ✖ Fetching webhooks data (1s)
      → NotFound: Status: 404 - Not Found - Message: The resource could not be found. - Request ID:[REDACTED]
      Fetching roles data
    Download assets
    Write export log file


The following 1 errors and 0 warnings occurred:

07:12:08 - Error: Status: 404 - Not Found - Message: The resource could not be found. - Request ID:[REDACTED]

🚨  Error: Errors occured
┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ContentfulMultiError: Errors occured                                                                                                        │
│     at /usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/contentful-export/dist/index.js:189:28  │
│     at tryCatcher                                                                                                                           │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/util.js:16:23)            │
│     at Promise._settlePromiseFromHandler                                                                                                    │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:547:31)        │
│     at Promise._settlePromise                                                                                                               │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:604:18)        │
│     at Promise._settlePromise0                                                                                                              │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:649:10)        │
│     at Promise._settlePromises                                                                                                              │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/promise.js:729:18)        │
│     at _drainQueueStep                                                                                                                      │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:93:12)           │
│     at _drainQueue                                                                                                                          │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:86:9)            │
│     at Async._drainQueues                                                                                                                   │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:102:5)           │
│     at Immediate.Async.drainQueues [as _onImmediate]                                                                                        │
│ (/usr/local/Cellar/contentful-cli/1.4.29/libexec/lib/node_modules/contentful-cli/node_modules/bluebird/js/release/async.js:15:14)           │
│     at processImmediate (internal/timers.js:439:21)                                                                                         │
└────────────────────────────────────────────────────────────────────────────

```

## Environment

-   **Language Version**: node v12.13
-   **Package Manager Version**: npm v6.12 (though, I installed using homebrew)
-   **Browser Version**: not relevant
-   **Operating System**: Catalina v10.15.5
-   **Package Version**: contentful v1.4.29

**Comment by sahellebusch** [comment]
This error was resolved by making me an admin of the space. Probably should be in the documentation somewhere.
